apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-azure-storageclass
  namespace: store-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: store-azure-storageclass
  interval: 1m
  chart:
    spec:
      chart: platforms/shared/charts/storage_class 
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
  values:
    metadata:
      name: store-azure-storageclass
    cloud_provider: azure
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowedTopologies:
      - matchLabelExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            values:
              - "eastus2a"
              - "eastus2b"
