apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychainvalidator2validator-node
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator2validator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_validator
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://fd359687f782e3204c96d597efcd585c74bb0e311d0fa0fc12f878cc3e27885dc63d67739681ed742c8538c54ca7181c66ad154ff5f149060b022ec8b5475ef3@validator1.supplychain-bes.svc.cluster.local:30303"
      - "enode://b968722b22180ba87202b894d4ba0c9e6a55fcf62165a552c2d225c4fbb2df13931f3c25833ba74ee69147bbc5ba6fc280c354c4aaa803e586879facd5fb9cb0@validator2.supplychain-bes.svc.cluster.local:30303"
      - "enode://e4e0d773e4cc6d7a49182a1d1359d993564c4f89e1f93f6d46233a5cf7ac37fe391806d171d408518c299ab2665fe098e0e3cde0431184263b49c47aba3dea31@validator3.supplychain-bes.svc.cluster.local:30303"
      - "enode://e3cb7b8e889d591cfa7ce9786a380c24e40e30ffa8a5f1a369c36371ca3b91c09cebfc3474714c950f208b577153fd53d5209e7121538e1f063f2b07bdd853e1@validator4.supplychain-bes.svc.cluster.local:30303"
      - "enode://f344326a74ca34f459700f20df80e68c505066c3589ebebcebd895ce2310e1cc0eed27b4b128a37a6b134a9392f1a98de86f3bf9dbc9e1127ccbca09eb1fb814@carrier.carrier-bes.svc.cluster.local:30303"
      - "enode://b40f58b7b1ecca5088596e4a181aeb12cb1e6c37ce0c6f177b3a88cd2768bb1894077e5b23c67f6b18c442ec669063e0962c12e00aae4e3688f9193424488043@manufacturer.manufacturer-bes.svc.cluster.local:30303"
      - "enode://2097a0e4b3253b2bef0f9f5f4637fda7b22a5ae427556403773bf74160fe4982da63e0a6e814ae178b6bd77a7dec1a1a5f6d26270b5c40e321f5308a18cd3a12@store.store-bes.svc.cluster.local:30303"
      - "enode://25ecf66bf88167ee18475f9d778e7a7990c35c76330b79be309f29067e731e6e8251d6c8ae5d53edbd3ee3cfd59d9210c705fa1aa39f22e2c5b2abe47220d42e@warehouse.warehouse-bes.svc.cluster.local:30303"

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: supplychain-bes.svc.cluster.local

    liveliness_check:
      enabled: false
    proxy:
      provider: none
      external_url: supplychain.supplychain-bes
      p2p: 30303
      rpc: 8545

    images:
      node: hyperledger/besu:22.10.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

      permissioning:
        enabled: False
      
    storage:
      storageclassname: supplychain-azure-storageclass
      storagesize: 1Gi

    vault:
      address: http://20.96.60.200:8200
      secretengine: secretsv2
      secretprefix: data/supplychain-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain
      type: hashicorp

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiYWxsb2MiOiB7CiAgICAiNWY5OTViZWYxOTFmRDE1OTVmZTQwYWZlODUzNWZjNDA2N0ZEOTQyMyI6IHsKICAgICAgImJhbGFuY2UiOiAiOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgIkIwOTBFYjQ3NjI3NjUwOTZBOTdiMUYyRTAzQzBlRTgwQUExOGRkRWMiOiB7CiAgICAgICJiYWxhbmNlIjogIjkwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgfQogIH0sCiAgImV4dHJhRGF0YSI6ICIweGY4N2VhMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBmODU0OTQxMTA5YjExMThhNDUwMDAwZjJhOTUwMjc4ZjE5ZGZjODg0OGY1YWMxOTQ5ZTJjZjY3OTE4OTllZjFjMzRiYmQ4Y2MyZjFlOTNlNDk5N2FjZjQyOTQyNTlkYWZiNzBmYTFiYmU4MTM5YTg1MzUzYTY3MzZlNzgyMGQyYzM3OTRkMWVkZDZjNDViMzM4MzBlMjMwMTZiNTY5NzAyYTAwYTQ3MTBhY2UzODA4NDAwMDAwMDAwYzAiCn0=

   
    labels:  
      service:
        - component: besu
      pvc:
      deployment:
        - owner: bevel
        - component: besu

    metrics:
      enabled: True
      port: 9545    
